# Site settings
title: Yeghishe Piruzyan's blog
author: Yeghishe Piruzyan
email: ypiruzyan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a software engineer based in Los Angeles. I'll be blogging about interesting technologies and challenges I face that others may find helpful.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yeghishe.github.io" # the base hostname & protocol for your site
twitter_username: ypiruzyan
github_username: yeghishe
google_username: ypiruzyan
linkedin_username: ypiruzyan

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->

highlighter: pygments

paginate: 10
sass:
  style: :compressed

timezone: America/Los_Angeles
host: 0.0.0.0
port: 9003

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', 'tmuxinator.yml']
gems: [jekyll-paginate, jekyll-gist, jekyll-sitemap, jekyll-assets]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "Yeghishe Piruzyan"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "drafts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "Yeghishe Piruzyan"

assets:
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  assets:
    - "*.png"
    - "bundle.css"
  digest: true
  sources:
    - _assets/css
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/img
    - _assets/js
  features:
    automatic_img_size: false
