# Site settings
title: Yeghishe Piruzyan
email: ypiruzyan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a software engineer based in Los Angeles. I'll be blogging about interesting technologies and challanges I face that other may find helpful.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yeghishe.github.io" # the base hostname & protocol for your site
twitter_username: ypiruzyan
github_username: yeghishe
google_username: ypiruzyan
linkedin_username: ypiruzyan

# Build settings
markdown: kramdown

paginate: 10
sass:
  style: :compressed

timezone: America/Los_Angeles
host: 0.0.0.0
port: 9003

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/about.md"
    - "/feed.xml"
    - "/css/main.scss"
  include_posts:
    - "/index.html"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "Yeghishe Piruzyan"

